apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-was-deployment
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
